# Summer Products Data Analysis

#### 1. Importing Libraries

#### 2. Loading the Dataset

#### 3. Understanding the Dataset

#### 4. Data Quality Assessment

#### 5. Data Cleaning

#### 6. Exploratory Data Analysis

#### 7. Statistical Analysis

#### 8. Data Visualization

#### 9. Correlation Analysis

#### 10. Final Insights

In [4]:
import pandas as pd #the primary Python library for tabular data manipulation

In [5]:
#loading the csv file
df = pd.read_csv("/Users/jayraj/Desktop/College/Summer_Product_Analysis/Retail-Sales-Analytics/data/raw/summer-products_2020-08.csv")

In [6]:
#for confirmation that it has been loaded:
df.head() #this shows the first 5 values of the dataset

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [7]:
#looking at the last rows
df.tail()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.0,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.0,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.0,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.0,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.0,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [8]:
df.sample(5) #this gives us any random 5 values

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
915,Femmes d'été Mode Débardeurs Sexy Sans Manches...,Women Summer Fashion Tank Tops Sexy Sleeveless...,2.0,2,EUR,1000,0,4.19,81,50.0,...,126370,4.146957,58ad449708de0c6dc59d9e06,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5e16cb87e6dd7c03be24b28a,https://contestimg.wish.com/api/webimage/5e16c...,5e16cb87e6dd7c03be24b28a,summer,2020-08
585,Décontracté Plage Décontracté col en V Mode sa...,Beach Casual V-neck Fashion Sleeveless Zipper ...,16.0,26,EUR,1000,0,3.67,450,184.0,...,12322,4.237543,595f3d28ce4e69232af53c32,0,NaN,https://www.wish.com/c/59636dbdc657d57012e8b3f3,https://contestimg.wish.com/api/webimage/59636...,59636dbdc657d57012e8b3f3,summer,2020-08
345,3 Couleurs De La Mode D'été Femmes Sexy Sans M...,3 Colors Fashion Summer Women Sexy Sleeveless ...,8.0,17,EUR,1000,1,3.93,426,216.0,...,5807,3.984157,5b6935c0a1fdaa1dba5a4cd4,0,NaN,https://www.wish.com/c/5c30694985fe9b55be100665,https://contestimg.wish.com/api/webimage/5c306...,5c30694985fe9b55be100665,summer,2020-08
52,Womens Fashion 3D Skull Print Cut Out Back Tan...,Womens Fashion 3D Skull Print Cut Out Back Tan...,1.0,11,EUR,1000,1,3.80,5,3.0,...,8197,3.858119,5684ca0f73c0e02989b91cad,0,NaN,https://www.wish.com/c/5ee717cbcb636e7b8b597fc3,https://contestimg.wish.com/api/webimage/5ee71...,5ee717cbcb636e7b8b597fc3,summer,2020-08
291,Femmes Dames D'été Sans Manches Longue Robe Pl...,Women Ladies Summer Sleeveless Long Dress Plus...,13.0,14,EUR,10000,0,3.74,1938,870.0,...,5466,3.941090,582d5286168b54404ec5ecf2,0,NaN,https://www.wish.com/c/5d1460e2aec1fd1f8cc82be5,https://contestimg.wish.com/api/webimage/5d146...,5d1460e2aec1fd1f8cc82be5,summer,2020-08

In [9]:
#to find the dimension of dataset, rows and columns
df.shape

(1573, 43)

In [10]:
# to get column names
df.columns.tolist() #here tolist help us to organize the data in a list format

['title',
 'title_orig',
 'price',
 'retail_price',
 'currency_buyer',
 'units_sold',
 'uses_ad_boosts',
 'rating',
 'rating_count',
 'rating_five_count',
 'rating_four_count',
 'rating_three_count',
 'rating_two_count',
 'rating_one_count',
 'badges_count',
 'badge_local_product',
 'badge_product_quality',
 'badge_fast_shipping',
 'tags',
 'product_color',
 'product_variation_size_id',
 'product_variation_inventory',
 'shipping_option_name',
 'shipping_option_price',
 'shipping_is_express',
 'countries_shipped_to',
 'inventory_total',
 'has_urgency_banner',
 'urgency_text',
 'origin_country',
 'merchant_title',
 'merchant_name',
 'merchant_info_subtitle',
 'merchant_rating_count',
 'merchant_rating',
 'merchant_id',
 'merchant_has_profile_picture',
 'merchant_profile_picture',
 'product_url',
 'product_picture',
 'product_id',
 'theme',
 'crawl_month']

In [11]:
#inspect data_types
df.dtypes

title                               str
title_orig                          str
price                           float64
retail_price                      int64
currency_buyer                      str
units_sold                        int64
uses_ad_boosts                    int64
rating                          float64
rating_count                      int64
rating_five_count               float64
rating_four_count               float64
rating_three_count              float64
rating_two_count                float64
rating_one_count                float64
badges_count                      int64
badge_local_product               int64
badge_product_quality             int64
badge_fast_shipping               int64
tags                                str
product_color                       str
product_variation_size_id           str
product_variation_inventory       int64
shipping_option_name                str
shipping_option_price             int64
shipping_is_express               int64
countries_shipped_to              int64
inventory_total                   int64
has_urgency_banner              float64
urgency_text                        str
origin_country                      str
merchant_title                      str
merchant_name                       str
merchant_info_subtitle              str
merchant_rating_count             int64
merchant_rating                 float64
merchant_id                         str
merchant_has_profile_picture      int64
merchant_profile_picture            str
product_url                         str
product_picture                     str
product_id                          str
theme                               str
crawl_month                         str
dtype: object

In [12]:
'''The first most imp command we should use in front of judges. the info command'''
df.info()
#"I used info() to inspect the structure of the dataset, identify data types, and identify columns containing missing values."

<class 'pandas.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   str
 1   title_orig                    1573 non-null   str
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   str
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1528 non-null   float64
 10  rating_four_count             1528 non-null   float64
 11  rating_three_count            1528 non-null   float64
 12  rating_two_count              1528 non-null   float64
 13  rating_one_count              1528 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   str
 19  product_color                 1532 non-null   str
 20  product_variation_size_id     1559 non-null   str
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   str
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            473 non-null    float64
 28  urgency_text                  473 non-null    str
 29  origin_country                1556 non-null   str
 30  merchant_title                1573 non-null   str
 31  merchant_name                 1569 non-null   str
 32  merchant_info_subtitle        1572 non-null   str
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   str
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      226 non-null    str
 38  product_url                   1573 non-null   str
 39  product_picture               1573 non-null   str
 40  product_id                    1573 non-null   str
 41  theme                         1573 non-null   str
 42  crawl_month                   1573 non-null   str
dtypes: float64(9), int64(15), str(19)
memory usage: 1.5 MB

In [13]:
'''Statistical overview'''
df.describe()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
count,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1528.000000,1528.000000,1528.000000,1528.000000,...,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,473.0,1.573000e+03,1573.000000,1573.000000
mean,8.325372,23.288620,4339.005086,0.432931,3.820896,889.659250,442.263743,179.599476,134.549738,63.711387,...,0.012715,33.081373,2.345200,0.002543,40.456453,49.821360,1.0,2.649583e+04,4.032345,0.143675
std,3.932030,30.357863,9356.539302,0.495639,0.515374,1983.928834,980.203270,400.516231,311.690656,151.343933,...,0.112075,21.353137,1.024371,0.050379,20.301203,2.562799,0.0,7.847446e+04,0.204768,0.350871
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,6.000000,1.000000,1.0,0.000000e+00,2.333333,0.000000
25%,5.810000,7.000000,100.000000,0.000000,3.550000,24.000000,12.000000,5.000000,4.000000,2.000000,...,0.000000,6.000000,2.000000,0.000000,31.000000,50.000000,1.0,1.987000e+03,3.917353,0.000000
50%,8.000000,10.000000,1000.000000,0.000000,3.850000,150.000000,79.000000,31.500000,24.000000,11.000000,...,0.000000,50.000000,2.000000,0.000000,40.000000,50.000000,1.0,7.936000e+03,4.040650,0.000000
75%,11.000000,26.000000,5000.000000,1.000000,4.110000,855.000000,413.500000,168.250000,129.250000,62.000000,...,0.000000,50.000000,3.000000,0.000000,43.000000,50.000000,1.0,2.456400e+04,4.161797,0.000000
max,49.000000,252.000000,100000.000000,1.000000,5.000000,20744.000000,11548.000000,4152.000000,3658.000000,2003.000000,...,1.000000,50.000000,12.000000,1.000000,140.000000,50.000000,1.0,2.174765e+06,5.000000,1.000000

In [ ]:
#Categorical overview
df.describe(include="object")
#This gives us information about text/categorical columns.

/var/folders/60/ycmgjz8n0534kzc8j593kflh0000gn/T/ipykernel_3232/1894647174.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,title,title_orig,currency_buyer,tags,product_color,product_variation_size_id,shipping_option_name,urgency_text,origin_country,merchant_title,merchant_name,merchant_info_subtitle,merchant_id,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
count,1573,1573,1573,1573,1532,1559,1573,473,1556,1573,1569,1572,1573,226,1573,1573,1573,1573,1573
unique,1201,1203,1,1230,101,106,15,2,6,958,957,1058,958,125,1341,1341,1341,1,1
top,Nouvelle mode d'été femmes robe décontractée c...,New Fashion Summer Women Casual Dress Round Ne...,EUR,"Summer,Fashion,Necks,Skirts,Dress,Loose,Women'...",black,S,Livraison standard,Quantité limitée !,CN,guangzhouweishiweifushiyouxiangongsi,广州唯适唯服饰有限公司,"83 % avis positifs (32,168 notes)",558c2cdc89d53c4005ea2920,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5c80e8a150c63d28c67b8f14,https://contestimg.wish.com/api/webimage/5c80e...,5c80e8a150c63d28c67b8f14,summer,2020-08
freq,24,24,1573,17,302,641,1508,472,1516,15,15,14,15,12,3,3,3,1573,1573

In [16]:
#we can also inspect
df["product_color"].value_counts()

product_color
black         302
white         254
yellow        105
blue           99
pink           99
             ...
violet          1
blackwhite      1
darkgreen       1
rosegold        1
gold            1
Name: count, Length: 101, dtype: int64