# Summer Products Data Analysis

#### 1. Importing Libraries

#### 2. Loading the Dataset

#### 3. Understanding the Dataset

#### 4. Data Quality Assessment

#### 5. Data Cleaning

#### 6. Exploratory Data Analysis

#### 7. Statistical Analysis

#### 8. Data Visualization

#### 9. Correlation Analysis

#### 10. Final Insights

In [ ]:
import pandas as pd #the primary Python library for tabular data manipulation

In [2]:
#loading the csv file
df = pd.read_csv("/Users/jayraj/Desktop/College/Summer_Product_Analysis/Retail-Sales-Analytics/data/raw/summer-products_2020-08.csv")

In [4]:
#for confirmation that it has been loaded:
df.head() #this shows the first 5 values of the dataset

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

In [5]:
#looking at the last rows
df.tail()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.0,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.0,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.0,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.0,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.0,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

In [7]:
df.sample(5) #this gives us any random 5 values

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
472,2019 nouvelles femmes mode pantalon lâche tail...,2019 New Women Fashion Loose Pants High Waist ...,12.00,11,EUR,20000,1,3.64,1711,702.0,...,55499,4.138885,5926c5ace8ff5525241b368d,0,NaN,https://www.wish.com/c/5cc40501e824b607860ec588,https://contestimg.wish.com/api/webimage/5cc40...,5cc40501e824b607860ec588,summer,2020-08
899,MXNINA Sexy Women's Summer Casual Sleeveless ...,MXNINA Sexy Women's Summer Casual Sleeveless ...,9.00,21,EUR,100,0,3.51,47,17.0,...,9827,4.113870,57c306d73a698c06f98ed450,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5936611a08f45940ce8b5e01,https://contestimg.wish.com/api/webimage/59366...,5936611a08f45940ce8b5e01,summer,2020-08
1475,Women's Fashion Fitness Gilet de fitness pour ...,Women's Fashion Fitness Vest Ladies Solid Tank...,3.81,59,EUR,5000,0,3.74,1444,591.0,...,139223,3.933581,5708773c3c02161b3f8c7900,0,NaN,https://www.wish.com/c/5b3f3a9205dff81785dba8e6,https://contestimg.wish.com/api/webimage/5b3f3...,5b3f3a9205dff81785dba8e6,summer,2020-08
1463,T-shirt femme 90's Letter Print Summer Cotton ...,Women's T-shirt 90's Letter Print Summer Cotto...,6.00,17,EUR,5000,0,4.24,1650,969.0,...,13308,4.155996,5911220e84aaef7ce5d732ef,0,NaN,https://www.wish.com/c/5ad99c58bd784c1ffb100601,https://contestimg.wish.com/api/webimage/5ad99...,5ad99c58bd784c1ffb100601,summer,2020-08
1486,Nouveau mode hommes pantalons d'été pantalons ...,New Fashion Mens Summer Pants Slacks Shorts Sp...,5.00,8,EUR,5000,1,3.51,747,270.0,...,5019,4.069536,56c55a76cce1893c1b8a1716,0,NaN,https://www.wish.com/c/5d7886997bf8ef73a437287a,https://contestimg.wish.com/api/webimage/5d788...,5d7886997bf8ef73a437287a,summer,2020-08

In [9]:
#to find the dimension of dataset, rows and columns
df.shape

(1573, 43)

In [10]:
# to get column names
df.columns

Index(['title', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='str')

In [11]:
#inspect data_types
df.dtypes

title                               str
title_orig                          str
price                           float64
retail_price                      int64
currency_buyer                      str
units_sold                        int64
uses_ad_boosts                    int64
rating                          float64
rating_count                      int64
rating_five_count               float64
rating_four_count               float64
rating_three_count              float64
rating_two_count                float64
rating_one_count                float64
badges_count                      int64
badge_local_product               int64
badge_product_quality             int64
badge_fast_shipping               int64
tags                                str
product_color                       str
product_variation_size_id           str
product_variation_inventory       int64
shipping_option_name                str
shipping_option_price             int64
shipping_is_express               int64
countries_shipped_to              int64
inventory_total                   int64
has_urgency_banner              float64
urgency_text                        str
origin_country                      str
merchant_title                      str
merchant_name                       str
merchant_info_subtitle              str
merchant_rating_count             int64
merchant_rating                 float64
merchant_id                         str
merchant_has_profile_picture      int64
merchant_profile_picture            str
product_url                         str
product_picture                     str
product_id                          str
theme                               str
crawl_month                         str
dtype: object